### ISSUE TITLE
Release new gem version

### ISSUE THREAD

**Issue by Masa331** [ucetnictvi-on-line/ico-validator#14]
We need to release new gem version with latest changes into rubygems

**Comment by boblin** [comment]
Kterou verzi? Aktualni verze 0.4.0 ( https://github.com/ucetnictvi-on-line/ico-validator/blob/master/ico-validator.gemspec#L7 ) je releasnuta.

**Comment by Masa331** [comment]
No.. https://rubygems.org/gems/ico-validator
tam je sice 0.4.0 ale to je verze z roku 2015 - takze tam asi aktualni master nebude. A tam to potrebujem dostat. Nekdo to musi buildonout, zvednout verzi, dat sem a pak pushnout do rubygems. Tohle jsem myslel

**Comment by Masa331** [comment]
takze to podle me je porad aktualni
